[project]
name = "mtd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "@val314159", email = "jmward@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "gevent-websocket>=0.10.1",
    "websocket-client>=1.8.0",
]

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"
