#!/usr/bin/env python3
import sys

from mtd.lib.task_store import complete_task, connect, dump, read_payload


def main():
    try:
        payload = read_payload()
        with connect() as con:
            task = complete_task(con, payload)
        sys.stdout.write(dump(task))
    except Exception as e:
        print(e, file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
