#!/usr/bin/env python3
import sys

from mtd.lib.task_store import connect, dump, get_agenda


def main():
    try:
        with connect() as con:
            agenda = get_agenda(con)
        sys.stdout.write(dump(agenda))
    except Exception as e:
        print(e, file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
