#!/usr/bin/env python3
import sys

from task_store import connect, dump, get_blocked


def main():
    try:
        with connect() as con:
            blocked = get_blocked(con)
        sys.stdout.write(dump(blocked))
    except Exception as e:
        print(e, file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
